Repository ExpTechTW/TREM-Lite, pull requests merged in 2024-05, with the labels that each got.

#22 Resurrect
  README.md
  src/core/index/action.js
  src/core/index/api.js
  src/core/index/client.jar
  src/core/index/core.js
  src/core/index/eew.js
  src/core/index/event.js
  src/core/index/globals.js
  src/core/index/loop.js
  src/core/index/main.js
  src/core/index/rts.js
  src/core/index/server.js
  src/core/setting/init.js
  src/core/setting/setting.js
  src/css/main.css
  src/css/setting.css
  src/main.js
  src/package.json
  src/resource/data/detection.json
  src/resource/data/region.json
  src/view/index.html
  src/view/setting.html
Labels: size/XXL

#24 edit: WebSocket disconnect handle fix and change map color
  README.md
  src/core/index/action.js
  src/core/index/api.js
  src/core/index/loop.js
  src/core/index/main.js
  src/core/index/server.js
  src/core/setting/setting.js
  src/css/main.css
  src/package.json
  src/view/index.html
Labels: size/M

#29 build: 2.0.0-pre.2
  src/package.json
Labels: size/XS
